# Generated by Django 5.2.15 on 2026-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('direct', 'Direct Expense'), ('indirect', 'Indirect Expense'), ('misc', 'Misc Expense')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='history_note',
            field=models.TextField(blank=True),
        ),
    ]
