# Generated by Django 5.2.14 on 2026-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
