# Generated by Django 5.2.15 on 2026-07-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('expected_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('follow_up_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_followups', to='projects.project')),
            ],
            options={
                'ordering': ('expected_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_type', models.CharField(choices=[('issue', 'Cash Issue'), ('expense', 'Cash Expense'), ('return', 'Cash Return'), ('settlement', 'Settlement')], max_length=20)),
                ('issued_to', models.CharField(max_length=255)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_entries', to='projects.project')),
            ],
            options={
                'ordering': ('-entry_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=120)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('revision_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_budgets', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
