# Generated by Django 5.2.15 on 2026-07-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_collectionfollowup_pettycash_projectbudget'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfollowup',
            name='forecast_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='collectionfollowup',
            name='history_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(choices=[('client_payment', 'Client Payment'), ('advance', 'Advance'), ('partial', 'Partial Payment'), ('final', 'Final Payment'), ('vendor', 'Vendor Payment'), ('labour', 'Labour Payment'), ('material', 'Material Payment'), ('equipment', 'Equipment Payment'), ('subcontractor', 'Subcontractor Payment'), ('misc', 'Misc Payment')], default='client_payment', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('flow_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_entries', to='projects.project')),
            ],
            options={
                'ordering': ('-flow_date', '-created_at'),
            },
        ),
    ]
