# Generated by Django 5.2.14 on 2026-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('labor_type', models.CharField(max_length=100)),
                ('worker_name', models.CharField(max_length=255)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('attendance_days', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('wage_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-work_date', '-created_at'),
            },
        ),
    ]
